### ISSUE TITLE
New link for button

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/VS#3]
Please link the "Listen Now" button in the menu bar of the OKCatholicBroadcasting.com site to http://stmichaelradio.com/stream/

**Comment by arish-ricom** [comment]
Hi Brett,

The domain is down.

http://okcathollicbroadcasting.com/

Found out that it has been expired. Please kindly renew the domain.

Thanks & Regards
Arish

**Comment by brettfarley** [comment]
http://okcatholicbroadcasting.com is not down. 

On Aug 7, 2015, at 1:44 AM, Syed Safdar Arish <notifications@github.com> wrote:

Hi Brett,

The domain is down.

http://okcathollicbroadcasting.com/ <http://okcathollicbroadcasting.com/>
Found out that it has been expired. Please kindly renew the domain.

Thanks & Regards
Arish

**Comment by arish-ricom** [comment]
Updated.

**Comment by brettfarley** [comment]
Oh, you changed the link for "Listen Online" in the left hand bar. But I need the button in the MENU BAR (the gif image with the headphones) to be linked also. Sorry for the confusion.

**Comment by arish-ricom** [comment]
Hi Brett,

I was looking at the menu when you said menu bar, but it actually is not menu bar, it is a block below the slider.

Anyway I corrected the mistake.

Thanks & Regards
Arish

**Comment by brettfarley** [comment]
Oh sorry, my bad. Ok, thanks!

On Aug 10, 2015, at 6:22 AM, Syed Safdar Arish <notifications@github.com> wrote:

Hi Brett,

I was looking at the menu when you said menu bar, but it actually is not menu bar, it is a block below the slider.

Anyway I corrected the mistake.

Thanks & Regards
Arish
