### ISSUE TITLE
update twitter feed in footer

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/VS#6]
Please ensure that the twitter feed is correctly display the veritsstrat feed in the footer.

**Comment by arish-ricom** [comment]
Dear Brett,

Currently it is just static HTML block without any dynamic elements.

I need twitter widget ID. You can find instruction on how to get twitter widget ID in the link below:
http://www.hunter.cuny.edu/hunter-webcms/learning/tutorials/how-do-i-find-my-twitter-widget-id

Thanks & Regards
Arish

**Comment by brettfarley** [comment]
Here you are: 687285221851398144

Here’s the full widget in case you need it: <a class="twitter-timeline" href="https://twitter.com/brettfarley" data-widget-id="687285221851398144">Tweets by @brettfarley</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

On Jan 13, 2016, at 1:31 AM, Syed Safdar Arish <notifications@github.com> wrote:

Dear Brett,

Currently it is just static HTML block without any dynamic elements.

I need twitter widget ID. You can find instruction on how to get twitter widget ID in the link below:
http://www.hunter.cuny.edu/hunter-webcms/learning/tutorials/how-do-i-find-my-twitter-widget-id <http://www.hunter.cuny.edu/hunter-webcms/learning/tutorials/how-do-i-find-my-twitter-widget-id>
Thanks & Regards
Arish

**Comment by brettfarley** [comment]
Also, please update the feed on this page too: http://veritasstrat.com/team/

**Comment by arish-ricom** [comment]
The feed is already updated as per latested feed at : https://twitter.com/veritasstrat

Note: I increased number of feeds from 6 to 10.

**Comment by arish-ricom** [comment]
Here you are: 687285221851398144
    Here’s the full widget in case you need it: <a class="twitter-timeline" href="https://twitter.com/brettfarley" data-widget-id="687285221851398144">Tweets by @brettfarley</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

Thanks. Added in footer.
